spring.application.name=AppEscuela
logging.pattern.dateformat=hh:mm
spring.main.banner-mode=off
#Conexión a PostGresql
spring.datasource.url=jdbc:postgresql://localhost:5432/sicacecsj
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect